/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoIndexRouteImport } from './routes/contacto/index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias/index'
import { Route as CatalogoIndexRouteImport } from './routes/catalogo/index'
import { Route as CatalogoProductSlugRouteImport } from './routes/catalogo/$productSlug'

const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoIndexRoute = ContactoIndexRouteImport.update({
  id: '/contacto/',
  path: '/contacto/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIndexRoute = CatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoProductSlugRoute = CatalogoProductSlugRouteImport.update({
  id: '/catalogo/$productSlug',
  path: '/catalogo/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$productSlug': typeof CatalogoProductSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/contacto/': typeof ContactoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$productSlug': typeof CatalogoProductSlugRoute
  '/catalogo': typeof CatalogoIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/contacto': typeof ContactoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$productSlug': typeof CatalogoProductSlugRoute
  '/catalogo/': typeof CatalogoIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/contacto/': typeof ContactoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/catalogo/$productSlug'
    | '/catalogo/'
    | '/categorias/'
    | '/contacto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/favoritos'
    | '/catalogo/$productSlug'
    | '/catalogo'
    | '/categorias'
    | '/contacto'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favoritos'
    | '/catalogo/$productSlug'
    | '/catalogo/'
    | '/categorias/'
    | '/contacto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FavoritosRoute: typeof FavoritosRoute
  CatalogoProductSlugRoute: typeof CatalogoProductSlugRoute
  CatalogoIndexRoute: typeof CatalogoIndexRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  ContactoIndexRoute: typeof ContactoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto/': {
      id: '/contacto/'
      path: '/contacto'
      fullPath: '/contacto/'
      preLoaderRoute: typeof ContactoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/': {
      id: '/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo/'
      preLoaderRoute: typeof CatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$productSlug': {
      id: '/catalogo/$productSlug'
      path: '/catalogo/$productSlug'
      fullPath: '/catalogo/$productSlug'
      preLoaderRoute: typeof CatalogoProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FavoritosRoute: FavoritosRoute,
  CatalogoProductSlugRoute: CatalogoProductSlugRoute,
  CatalogoIndexRoute: CatalogoIndexRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  ContactoIndexRoute: ContactoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
